name: Build and Run Qt Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      run: |
        choco install qt5

    - name: Build Qt application
      run: |
        qmake QtDemoApp.pro -r CONFIG+=debug
        nmake

    - name: Deploy Qt application
      run: |
        windeployqt .\debug\QtDemoApp.exe

    - name: Run Qt application
      run: .\debug\QtDemoApp.exe
