name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Qt using the Qt Online Installer
        run: |
          # Scarica il Qt Installer (versione 5.15.2)
          Invoke-WebRequest -Uri https://download.qt.io/official_releases/qt/5.15/5.15.2/qt-opensource-windows-x86-5.15.2.exe -OutFile qt-installer.exe
          Start-Process -FilePath qt-installer.exe -ArgumentList "/S" -Wait

      - name: Set up environment variables for Qt
        run: |
          # Imposta le variabili d'ambiente per Qt
          $env:PATH += ";C:\Qt\5.15.2\mingw81_64\bin"  # Modifica se la tua installazione Qt è in una directory diversa
          $env:QTDIR = "C:\Qt\5.15.2"

      - name: Build with qmake
        run: |
          qmake QtDemoApp.pro -r CONFIG+=debug
          make

      - name: Archive Debug artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-artifacts
          path: debug/QtDemoApp.exe

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download debug artifacts
        uses: actions/download-artifact@v3
        with:
          name: debug-artifacts

      - name: Deploy with windeployqt
        run: |
          windeployqt .\debug\QtDemoApp.exe

      - name: Upload deployed artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deployed-debug-artifacts
          path: debug/**

  run:
    runs-on: windows-latest
    needs: deploy

    steps:
      - name: Download deployed artifacts
        uses: actions/download-artifact@v3
        with:
          name: deployed-debug-artifacts

      - name: Run the application
        run: |
          .\debug\QtDemoApp.exe
