name: Build and Run Qt Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default qt5-qmake

    - name: Build Qt application
      run: |
        qmake QtDemoApp.pro
        make

    - name: Run Qt application
      run: ./QtDemoApp
